### ISSUE TITLE
No autocompletion in flatplak

### ISSUE THREAD

**Issue by drahnr** [deikatsuo/bracer#1]
Despite following the tutorial, autocompletion does not work.

All UI elements in the config pane are visible, yet no autocompletion is happening.

**Comment by deikatsuo** [comment]
you need racer to be installed, or else this extension won't work

**Comment by deikatsuo** [comment]
Oh.. you are right.. it seems this extension doesn't work anymore.. There are some changes to builder which separate the workbench preferences from the main workbench and since then this extension got broken. 

hhhh... I will try to fix this when I have free time

**Comment by drahnr** [comment]
```
cargo install racer
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing racer v2.0.10
error: binary `racer` already exists in destination as part of `racer v2.0.10`
Add --force to overwrite
```

```
cargo install rls
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing rls v0.122.2
error: binary `rls` already exists in destination as part of `rls v0.122.2`
Add --force to overwrite
```


```
rustup component add --toolchain=stable rust-src
info: component 'rust-src' is up to date
```

```
rustup component add --toolchain=nightly rust-src
info: component 'rust-src' is up to date
```

```
exa -1  ~/.local/share/gnome-builder/plugins/bracer
README.md
Screenshot
__pycache__
bracer.plugin
bracer.py
resources
schema
```

Anything I am missing out on? I am running Fedora 26 x86_64.

**Comment by deikatsuo** [comment]
try run builder on terminal and see if there is any error message
flatpak run org.gnome.Builder

**Comment by drahnr** [comment]
```
15:47:17.0979                                   libpeas[22550]:  WARNING: Error importing plugin 'bracer':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 879, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/bernhard/.local/share/gnome-builder/plugins/bracer/bracer.py", line 20, in <module>
    from gi.repository import Dazzle
  File "/usr/lib64/python3.6/site-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Dazzle, introspection typelib not found
15:47:17.0980                                   libpeas[22550]:  WARNING: Error loading plugin 'bracer'
jedi not found, python auto-completion not possible.
```

**Comment by drahnr** [comment]
I also installed `gnome-builder-devel` which did not make a difference.

**Comment by deikatsuo** [comment]
Oh, it seems you haven't installed libdazzle

**Comment by deikatsuo** [comment]
or try builder nightly https://git.gnome.org/browse/gnome-apps-nightly/plain/gnome-builder.flatpakref

I think I should rewrite this extension, there are too many bugs in the current code

**Comment by albe-rosado** [comment]
im getting this when running in the console, (flatpak version):

`
Builder Workbench Addin: Load Bracer plugin workbench
Traceback (most recent call last):
  File "/home/albe/.local/share/gnome-builder/plugins/bracer/bracer.py", line 302, in do_load
    if Bracer.settings.get_boolean('prefs-documentation'):
AttributeError: type object 'Bracer' has no attribute 'settings'
`
